server  {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ibulak.42.fr;
    root /var/www/wordpress;

    ssl_certificate     /etc/nginx/ssl/ibulak.crt
    ssl_certificate_key /etc/nginx/ssl/ibulak.key
    ssl_protocols TLSv1.2 TLSv1.3;

    # ssl_ciphers
    # HIGH:!aNULL:!MD5;

    location /  {
        try_files $uri $uri/ = 404;
    }

    location ~ \.php$  {
        fastcgi_pass wordpress:9000;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
